// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_SFj4U7cg-GfVZaZqjvGP6OvPSoHQCs',
    appId: '1:299527331134:web:0bac83f059687017b0a06f',
    messagingSenderId: '299527331134',
    projectId: 'movieflutterapp-6dd32',
    authDomain: 'movieflutterapp-6dd32.firebaseapp.com',
    storageBucket: 'movieflutterapp-6dd32.appspot.com',
    measurementId: 'G-72N4L5TND5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOajmU4e1JUyB8ui-nUsBO_W82b_Kov0',
    appId: '1:299527331134:android:2efb3a3fd366ee99b0a06f',
    messagingSenderId: '299527331134',
    projectId: 'movieflutterapp-6dd32',
    storageBucket: 'movieflutterapp-6dd32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKp0DuqNnTSDC_-_D0Dpvv7HSnsfmUkDg',
    appId: '1:299527331134:ios:5a34843f87a34da0b0a06f',
    messagingSenderId: '299527331134',
    projectId: 'movieflutterapp-6dd32',
    storageBucket: 'movieflutterapp-6dd32.appspot.com',
    iosClientId: '299527331134-apub1qjh6o9kpm7mqvpbt7s447nvk5ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieFlutterApplication',
  );
}
